### PR TITLE
Feature/new osm data

### PR DESCRIPTION
**Pull request by svevang**
This PR introduces a new file based source of osm fountain data.  The data was parsed from OSM using https://github.com/wetap/osm_water_fountains.  

Using [this python snippet](https://gist.github.com/svevang/c91e9acf7ba99ca28a06), I parsed the json output and built a csv file that's compatible with our `water_fountain_importer`.

### CODE REVIEW

**Comment by michaelkirk** [comment]
Awesome @svevang. I forgot it was already Friday! Thanks for your work here.

When do you want to run it in production?

Two thoughts on the import:
1. snag a fresh db backup before import.
2. The dyno import process might balloon and explode. I don't think that import script is very optimal.

**Comment by svevang** [comment]
I ran the new data import script on production and can verify the new and old data is present in the admin interface.  I'll run home and check out the app (I forgot my phone at home).

**Comment by michaelkirk** [comment]
Cool. Nice work!

**Comment by jmoody** [comment]
@svevang :pizza: 

Thanks!

**Pull request merged**
